version: "3.8"
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - network-backend
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  db:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: engineer
      MONGODB_INITDB_ROOT_PASSWORD: strongpassword
    networks: 
     - network-backend
networks:
  network-backend:
volumes: 
  mongodb_data:
