apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: finalproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "/api"
